version: 2

jobs:
  demonstration:
    docker:
    - image: circleci/python:3.7-strech-node
    steps:
    - setup_remote_docker:
          version: << parameters.docker-version >>
    - run:
        command: docker version
        name: Test out API support

workflows:
  all-dockers:
    jobs:
      - demonstration:
          matrix:
            parameters:
              docker-version: 
              - 17.03.0-ce
              - 17.05.0-ce
              - 17.06.0-ce
              - 17.06.1-ce
              - 17.07.0-ce
              - 17.09.0-ce
              - 17.10.0-ce
              - 17.11.0-ce
              - 17.12.0-ce
              - 17.12.1-ce
              - 18.01.0-ce
              - 18.02.0-ce
              - 18.03.0-ce
              - 18.03.1-ce
              - 18.04.0-ce
              - 18.05.0-ce
              - 18.06.0-ce
              - 18.09.3
              - 19.03.8

